### ISSUE TITLE
README Clarifications

### ISSUE THREAD

**Issue by bmullan** [Ne00n/pipe-builder-3000#1]
Sorry got to ask...

In the README you say in the **Prepare** section:

> Rename hosts.example.json to hosts.json and fill it up

Not having used json much in the past where do I put this **_hosts.json_** file?   

Then you say...

> You can use * if you want to cross-connect to everything else

So I made my **hosts.json** file look like:

> {
>  "vm1":{"Targets":[*]},
>  "vm2":{"Targets":[*]},
>  "vm3":{"Targets":[*]},
> }

If I want everyone to connect to everyone is the above syntax correct?

Thanks
Brian

**Comment by Ne00n** [comment]
That's incorrect.
First you specify the Node, then with Targets you specify the Targets.

You can either use:
 "vm1":{"Targets":["vm2","vm3"]},

or In your case:
 "vm1":{"Targets":["*"]},
 "vm2":{"Targets":["*"]},
 "vm3":{"Targets":["*"]},

Which cross-connects everything with everything.
You could also use:

 "vm1":{"Targets":["*"]},
 "vm2":{"Targets":["*"]},
 "vm3":{"Targets":["*","vm4"]},

etc..

**Comment by bmullan** [comment]
Thanks so much.   I guess json is added to my list of 1000 things to learn :+1:

**Comment by Ne00n** [comment]
Yeah, they work together, one does the network setup, the other one takes care of the routing.

**Comment by Ne00n** [comment]
ReadMe has been updated.
